### ISSUE TITLE
.DS_Store causes error

### ISSUE THREAD

**Issue by benallfree** [dsktschy/laravel-mix-copy-watched#2]
I have a `.DS_Store` file in my source folder. It causes this error:

```js
mix.copyDirectoryWatched('src', 'dist')
```

```
 	Copying src/plugin/.DS_Store to dist

fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, unlink '/project/dist'
    at Object.unlinkSync (fs.js:952:3)
    at mayCopyFile (/project/node_modules/fs-extra/lib/copy-sync/copy-sync.js:57:8)
    at onFile (/project/node_modules/fs-extra/lib/copy-sync/copy-sync.js:52:10)
    at getStats (/project/node_modules/fs-extra/lib/copy-sync/copy-sync.js:46:44)
    at startCopy (/project/node_modules/fs-extra/lib/copy-sync/copy-sync.js:36:10)
    at Object.copySync (/project/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:10)
    at CopyFilesTask._copyFile (/project/node_modules/laravel-mix-copy-watched/src/copy-files-task.js:67:8)
    at FSWatcher.emit (events.js:182:13)
    at FSWatcher.EventEmitter.emit (domain.js:441:20)
    at FSWatcher.<anonymous> (/project/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/project/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/project/node_modules/chokidar/lib/fsevents-handler.js:329:12)
    at FSWatcher.<anonymous> (/project/node_modules/chokidar/lib/fsevents-handler.js:372:11)
    at ReaddirpReadable.emit (events.js:182:13)
    at ReaddirpReadable.EventEmitter.emit (domain.js:441:20)
    at addChunk (/project/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/project/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at ReaddirpReadable.Readable.push (/project/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at ReaddirpReadable.proto._processEntry (/project/node_modules/readdirp/stream-api.js:51:8)
    at /project/node_modules/readdirp/readdirp.js:237:15
    at Array.forEach (<anonymous>)
    at /project/node_modules/readdirp/readdirp.js:235:12
    at /project/node_modules/readdirp/readdirp.js:193:38
    at /project/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
```

**Comment by dsktschy** [comment]
@benallfree
I am fixing this problem.
It will be included in the next release.
Thank you.

**Comment by dsktschy** [comment]
@benallfree
Sorry for the late.
This problem is resolved on v.2.1.1.
Thank you.
