### ISSUE TITLE
throws exception  Cannot mix BigInt and other types, use explicit conversions

### ISSUE THREAD

**Issue by MordiSacks** [dsktschy/laravel-mix-copy-watched#9]
```
(node:17312) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\path\to\project\node_modules\@dsktschy\chokidar\index.js:771:36)
    at WatchHelper.filterPath (C:\path\to\project\node_modules\@dsktschy\chokidar\index.js:182:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\path\to\project\node_modules\@dsktschy\chokidar\lib\nodefs-handler.js:396:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\path\to\project\node_modules\readdirp\index.js:239:31)
    at ReaddirpStream._exploreDirectory (C:\path\to\project\node_modules\readdirp\index.js:166:23)
(node:17312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
t a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)


```

Node version: v10.16.0
Laravel mix: 4.0.7
laravel-mix-copy-watched: 2.1.6

It seams the issue has somthing to do with [chokidar](https://github.com/paulmillr/chokidar)

**Comment by dsktschy** [comment]
@MordiSacks 
Thank you for reporting.
I didn't reproduce on the same environment as you.
Can you tell me what you do when this error occured?
And can you share your webpack.mix.js?

**Comment by MordiSacks** [comment]
@dsktschy 
the issue happens on watch command only,
it copies all the files as expected but does not see any change
here is my webpack
```js
const mix = require('laravel-mix');

require('laravel-mix-copy-watched');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
    .setResourceRoot(process.env.APP_URL + `/${process.env.section}/`)
    .setPublicPath(`public/${process.env.section}`)
    .extract([
        'bootstrap',
        'jquery',
        'popper.js',
        'slick-carousel',
    ])
    .js(`resources/mixes/${process.env.section}/js/app.js`, `public/${process.env.section}/js`)
    .sass(`resources/mixes/${process.env.section}/scss/app.scss`, `public/${process.env.section}/css`)
    .copyWatched(
        `resources/mixes/${process.env.section}/images/**/*`,
        `public/${process.env.section}/images`,
        {base: `resources/mixes/${process.env.section}/images`}
    )
;

```

**Comment by dsktschy** [comment]
@MordiSacks 
I released v2.2.0.
Please update and retry.

Until v2.2.0, laravel-mix-copy-watched has used forked chokidar.
v2.2.0 or later, it uses original chokidar.
Because the problem that prevents the dot option to work correctly was resolved.

Maybe the error you encountered is this.
https://github.com/paulmillr/chokidar/issues/868
And this error has already been resolved in this commit.
https://github.com/spriggsey/chokidar/commit/6c6babafdcb949033c6d0ccd2c86d23a5a90e67f
So if laravel-mix-copy-watched uses the newest original chokidar, this error will not occur.

**Comment by MordiSacks** [comment]
@dsktschy 
Fixed!
Thank you for a great plugin!

**Comment by dsktschy** [comment]
@MordiSacks 
Thank you for using!

@spriggsey 
Maybe you no longer need to use forked package!
